# Generated by Django 2.2.5 on 2021-04-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiveMedicineToPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_number_of_medicine', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_medicine', models.IntegerField(verbose_name='Number of Medicine')),
                ('mg', models.CharField(max_length=20, verbose_name='Medicine MG')),
                ('expiry_date', models.DateField(verbose_name='Medicine Expiry Date')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Donor Location')),
                ('is_collected', models.BooleanField(blank=True, null=True, verbose_name='Agent Collected')),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.MedicineName')),
                ('medicine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.MedicineType')),
            ],
        ),
    ]
